name: Unit Tests

on:
  push:
    branches: [ "main" ]
    # tags: [ 'v*.*.*' ]
    
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install zig latest
        uses: mlugg/setup-zig@v1
      - name: Install libzmq
        run: |
          sudo apt update && sudo apt -y install libzmq3-dev
      - name: Install libduckdb
        run: |
          mkdir /tmp/duckdb
          sudo mkdir -p /usr/local/duckdb/lib
          sudo mkdir -p /usr/local/duckdb/include
          wget -nv -O /tmp/duckdk.zip https://github.com/duckdb/duckdb/releases/download/v1.0.0/libduckdb-linux-amd64.zip
          unzip /tmp/duckdk.zip -d /tmp/duckdb
          sudo mv /tmp/duckdb/lib* /usr/local/duckdb/lib/
          sudo mv /tmp/duckdb/*.h /tmp/duckdb/*.hpp /usr/local/duckdb/include/
      - name: Install libcatch2
        run: sudo apt-get -y install catch2
      - run: zig build test-all -Dduckdb_prefix=/usr/local -Dzmq_prefix=/usr --verbose
